// <auto-generated />
namespace AttendanceSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class v223 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v223));
        
        string IMigrationMetadata.Id
        {
            get { return "202003122001200_v2.23"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
