// <auto-generated />
namespace AttendanceSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class v2updatedstudentanddeparment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v2updatedstudentanddeparment));
        
        string IMigrationMetadata.Id
        {
            get { return "202003121210493_v2updatedstudentanddeparment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
