// <auto-generated />
namespace AttendanceSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class v22 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v22));
        
        string IMigrationMetadata.Id
        {
            get { return "202003121625470_v2.2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
